### ISSUE TITLE
Reading goal should only use points earned by reading.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#151]
(assign to me)

**Expected**
Reading points earn progress towards reading goal.

**Actual**
All points, regardless of source result in progress towards reading goal.

**Description**
This is a misunderstanding on my part on how points were earned. I did not realize that points could come from so many sources, this is misleading because it allows progress to be recorded on the "reading goal" without reading. Only patron points from reading should be counted towards the goal. "Overall goal" label should probably be changed to "reading goal".

**Comment by justinmeiners** [comment]
Does this bug fit your expectations about how the feature is supposed to work?

**Comment by haraldnagel** [comment]
We aren't real picky here about how people earn points - we obviously encourage reading as the cornerstone (especially for children) - but in our program points earned by participating in Adventures, Challenges, and Events all count towards our program prizes.

I can see it going either way and I don't have a problem with changing the verbiage on this to "reading goal" and taking that approach. I'd prefer to not make changes to the database right this minute since our site is live now but I can worth with it if we do. :smile:

**Comment by justinmeiners** [comment]
Ok that makes sense, and I understand the database issue.

For our library it is important that the goal is just tied to reading, so I may just make the change for my library.
