### ISSUE TITLE
"Ways to earn this badge" does not account for badges dependent on other badges.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#156]
If you setup an award trigger that awards a badge dependent only on other badges being earned, the text describing how to earn the badge says "Learn the secret code to unlock it". 

The text should describe that this badge is awarded by earning other badges or at least not a misleading description.

**Comment by haraldnagel** [comment]
You are right. I took the wrong approach with using "learn the secret code" as the default becuase I assumed that the only way it wouldn't be one of the other options was if the badge itself was hidden. :rage3:

**Comment by haraldnagel** [comment]
- Award Triggers are only displaying the name of the Award Trigger and not any of the criteria used
- "Learn the secret code to unlock it" should only be shown if the way to unlock it is a hidden event
- There's nothing to show here if a badge is made and has no way to award it (e.g. if it's going to be awarded with a Manual Award)

Ultimately:

- [GRA.Logic.Badge](https://github.com/haraldnagel/greatreadingadventure/blob/master/GRA.Logic/Badge.cs) needs to be fixed to show how to properly earn the badge or return `NULL` or an empty string if it can't be specified (I'm not sure if the Award Trigger portion is worth doing because those rules can be quite complex)
- `GRA.SRP.Badges.Details` and `GRA.SRP.Handlers.GetBadgeInfo` should both be modified to not display the "Ways to earn this badge" bit at all if `GRA.Logic.Badge` returns `NULL` or an empty string.
