### ISSUE TITLE
String resource files should have greater coverage. 

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#194]
Quite a bit of code hard codes strings rather than using the string resources, even in cases when change it would be trivial. This should be improved to allow greater customization and easier maintenance. 

I would be happy to help with this one in the future, I am just recording it as a reminder.

**Comment by haraldnagel** [comment]
This is a good thing to discuss.

I'm not sure if it makes sense to continue using the homegrown resource methodology that's currently in the application or maybe migrate to a Gettext-based approach ([i18n](https://github.com/turquoiseowl/i18n) or [NGettext](https://github.com/neris/NGettext) perhaps?).

Advantages:
- More standard approach
- Provide an easy interface for translations into other languages
- Cut down on viewstate size
- I'd assume an improvement in performance since the current method walks nearly the entire control tree every time the substitution call is made

**Comment by justinmeiners** [comment]
I am not familiar with ASP/.NET libraries, but It sounds like either would be better than the homegrown model, especially if that is how the substitution iteration works. 

Could you explain to me viewstate size? I have noticed that you have mentioned it a few times recently. I understand that it is used to preserve state across refreshes/posts etc but I am not aware of where it is stored. Is it stored on the server in some kind of session memory/file? Or is it data kept in hidden fields on the page?

**Comment by haraldnagel** [comment]
Viewstate is used to save data between page postbacks in Base64-encoded hidden form fields. Most controls marked `runat="server"` are going to store state information in the viewstate. In this case, all those `<asp:Label>` tags which have their `Text` property changed with `TranslateStrings(this)` have those updated values stored in the viewstate so that it persists between page postbacks (hence why `TranslateStrings(this)` is in an `if (!IsPostBack)` - they only need to be looked up once for the page and then they're maintained in the viewstate).

We ended up with our events page being ridiculously large because I wasn't originally being careful enough with viewstate and we had controls with it enabled where it didn't need to be. It would be ideal in situations like the registration page, for example, to find a way to reduce the amount of viewstate going back and forth on every postback.
