### ISSUE TITLE
Control Room Patron Edit uses different email regex then Patron Registration

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#200]
**Description**

Related to #192 

The Patron Registration process uses a different regular expression for validating emails than the patron editor in the control room. This creates the situation where it is impossible to edit patrons with certain email addresses.

https://github.com/MCLD/greatreadingadventure/blob/master/SRP/ControlRoom/Controls/PatronCtl.ascx

**Additional Discussion**

This isn't about this issue in particular, but more of a general problem, but it appears that quite a few bugs come from duplicated functionality across the project. The Patron Registration process is slightly different from "Add a Family member". The normal reading log is slightly different from the family reading log. The page versions of badges and challenges are separate from the popup versions. Is there any way we can  mitigate this problem in the future?

**Comment by justinmeiners** [comment]
Moving logic code out of the interfaces into their own business layers sounds like a great option to me. 

In my experience, transforming fragmented code to single point of truth is huge win in itself. I am not too familiar with testing in this kind of app (I have only used it with individual algorithms) but if it would be easy to implement im sure the benefits would be great.

**Comment by haraldnagel** [comment]
Testing this project seems complicated to me due to the way it was designed (?) and implemented. Some difficulties:

1. Lots of options in configuration - really need to configure the software in a bunch of ways to perform conclusive testing (e.g. does feature `x` work in these environments: single program, multiple programs, single program in a tenant, multiple programs with multiple tenants, etc).

2. A lot of logic is built into the front-end of the site which makes programmatically testing painful (you'd have to test by pushing clicks and keystrokes into a browser I suspect - you can't just call `LogMinutes(10)` and check the response to see if it's valid or threw an exception).

3. A lot of logic is built into stored procedures meaning that (as far as I know) there's no easy way to test them in a standalone basis unless you do all kinds of database pre-configuration and then post-examination.

4. Doing software test in a project which relies so heavily on the database (with no mocking/dependency injection) makes it challenging to write abstract tests (can't test logging minutes if you haven't already created a patron record or run the test that creates a patron record).

I bring up test because an ideal way to refactor huge amounts of things as we're discussing is to write some pretty in-depth tests and ensure they all work. Then as code is refactored you can ensure that you've done it properly when the tests all pass. This is also a concern of mine with refactoring the data model.

**Comment by justinmeiners** [comment]
Oh I certainly agree. Those kinds of things seem to make the project not a good fit for testing. That is why I mentioned earlier I am unfamiliar with testing this sort of thing.
