### ISSUE TITLE
Cleanup DAL system

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#40]
In several files I noticed that many methods have a large amount of code duplicated between them for reading and writing data to/from SQL queries. Could all these be condensed into one function for reading from and one for writing to a SQL query? I am aware that sometimes their are slight design inconsistencies that make this difficult, but from my file diffs they do look very similar.

Here are a few examples:
**Patron.cs**
- public static Patron GetObjectByUsername(string logon);
- public bool Fetch(int PID);
- public static Patron FetchObject(int PID);
- public static Patron GetObjectByEmail(string email);

**Badge.cs**
- public static int Insert(Badge o);
- public static int Update(Badge o);

**Badge.cs**
-  public static Badge GetBadge(int BID);
-  public bool Fetch(int BID);
-   public static Badge FetchObject(int BID);

**Comment by haraldnagel** [comment]
I have a lot of issues with the current manual [DAL model](https://en.wikipedia.org/wiki/Data_access_layer) in the GRA code (which I suspect was initially generated from a tool anyways). One of my "big picture" task items is to refactor this aspect of the application completely and move to a more integrated [ORM-type solution](https://en.wikipedia.org/wiki/Object-relational_mapping) (I'm leaning towards Microsoft's [Entity Framework](https://msdn.microsoft.com/en-us/data/ef.aspx)). In such a move, all of this boilerplate DAL code (and the stored procedures) would be eliminated and replaced with a simpler and cleaner data model.

I think that's the right approach though it's not something I'm ready to tackle just yet since I know we have some other changes which take the priority here. I'm envisioning this more as a change for the next major release.

**Comment by justinmeiners** [comment]
Ok, that sounds like that would make sense. If I improved some of the current code by removing duplication (in a fork of your branch) would that be helpful in the short term?

**Comment by haraldnagel** [comment]
You could but I'm not sure that it's worth it - I don't think the duplicated code is causing much of a performance issue.

**Comment by justinmeiners** [comment]
Ok I won't worry about it then. I wasn't thinking of it in terms of performance but maintainability and modification. I will probably be adding a few fields so it could be error prone to copy-paste often.
