### ISSUE TITLE
Generalize Registration Settings

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#71]
This is a general recommendation about a potential enhancement. The **RegistrationSettings** class and accompanying ControlRoom class has duplicate code and fields for each individual option. This makes it difficult to modify and maintain.

 I can't help but think this could be generalized into a single key/value dictionary for storage and manipulation purposes. Specific keys would still need to be checked and handled individually during the registration process itself, but I think it would help clean up storage.

Example:

Instead of:

```
RegistrationSettings
{
   ZipCode_Edit
   ZipCode_Prompt
   ZipCode_Req
   ZipCode_Show
   State_Edit
   ...
}
```

Perhaps it could be:

```
RegistrationField
{
    Edit
    Prompt
    Req
    Show
}

RegistrationSettings
{
    Dictionary<String, RegistrationField> fields;
}

```

**Comment by haraldnagel** [comment]
I agree with you that this would be a much cleaner way of handling this and it's something I'd like to see done. I think we should probably have a "wish list" of things to address after this year's summer reading program starts so that we can take on architectural changes like this (I'm assuming this isn't something you want to try to get done before summer reading starts).
